import os
from parser import *

source = open("source", "r")
output = open("main.asm", "w")

opened=0

loop = []

#intialse file
output.write(";do not edit this file is automaticly generated\n")
output.write("section .text \n")
output.write("	global _start \n")
output.write("_start:\n")
output.write("	mov ecx, [x] \n	mov edx, 0 \n")

data=""
for line in source:
	line=line.strip()
	for char in line:
		if(char=='<'): data+='<'
		elif(char=='>'): data+='>'
		elif(char=='+'): data+='+'
		elif(char=='-'): data+='-'
		elif(char==','): data+=','
		elif(char=='.'): data+='.'
		elif(char=='['): 
			output.write(f'.loop{str(opened)}: \n')
			loop.append("loop"+str(opened))
			data+='['
			opened+=1
		elif(char==']'): 
			output.write(f'	cmp ecx, [zero]\n')
			output.write(f'	je .con{loop[-1]}\n')
			output.write(f'	jmp .{loop[-1]}\n')
			output.write(f'.con{loop.pop()}:\n')
			data+=']'

#end file
output.write("	mov eax, 1\n")
output.write("	int 0x80\n")
output.write("section	.data\n")
output.write(";	global x\n")
output.write("	x times 3000 dd 0\n")
output.write("	zero dd 0\n")

output

parser(data)

os.system("make")